spring:
    jpa:
        database: MYSQL
        hibernate:
          ddl-auto: create 

    datasource:
       url: jdbc:mysql://localhost:3306/springboot?useSSL=false 
       username: root
       password: Sopra
       driverClassName: com.mysql.jdbc.Driver
         
         

         
         
         
         